language: ruby
cache: bundler
dist: trusty

branches:
  only:
    - master


rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
  - rvm: 2.2.7
    env: TRAVIS_CHEF_VERSION="~> 13.0"

before_install:
- gem update --system
- gem update bundler
- gem --version

script:
  - bundle exec rake

env:
  matrix:
  - TRAVIS_CHEF_VERSION="~> 12.0" # latest 12.x.y
  - TRAVIS_CHEF_VERSION="~> 13.0" # latest 13.x.y
  - TRAVIS_CHEF_VERSION="branch:v12.19.36" # chef-server stable
